apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/Documents/volumes/static/images"

